### PR TITLE
Support PHP 8.2

### LINKED ISSUE #9: Support PHP 8.2
As of PHP 8.2 [dynamic properties is deprecated](https://wiki.php.net/rfc/deprecate_dynamic_properties) and will be removed in the future. Notice:
```
[2023-02-13T12:24:50]:NOTICE: E_DEPRECATED: Creation of dynamic property Imefisto\PsrSwoole\ServerRequest::$swooleRequest is deprecated {"code":8192,"message":"Creation of dynamic property Imefisto\\PsrSwoole\\ServerRequest::$swooleRequest is deprecated","file":"/app/vendor/imefisto/psr-swoole-native/src/Request.php","line":20}
[2023-02-13T12:24:50]:NOTICE: E_DEPRECATED: Creation of dynamic property Imefisto\PsrSwoole\ServerRequest::$uriFactory is deprecated {"code":8192,"message":"Creation of dynamic property Imefisto\\PsrSwoole\\ServerRequest::$uriFactory is deprecated","file":"/app/vendor/imefisto/psr-swoole-native/src/Request.php","line":21}
[2023-02-13T12:24:50]:NOTICE: E_DEPRECATED: Creation of dynamic property Imefisto\PsrSwoole\ServerRequest::$streamFactory is deprecated {"code":8192,"message":"Creation of dynamic property Imefisto\\PsrSwoole\\ServerRequest::$streamFactory is deprecated","file":"/app/vendor/imefisto/psr-swoole-native/src/Request.php","line":22}
[2023-02-13T12:24:50]:NOTICE: E_DEPRECATED: Creation of dynamic property Imefisto\PsrSwoole\ServerRequest::$uploadedFileFactory is deprecated {"code":8192,"message":"Creation of dynamic property Imefisto\\PsrSwoole\\ServerRequest::$uploadedFileFactory is deprecated","file":"/app/vendor/imefisto/psr-swoole-native/src/ServerRequest.php","line":23}
```
I would add these variables to `Imefisto\PsrSwoole\ServerRequest`
```
    public $uploadedFileFactory;
    public $cookies;
    public $query;
    public $files;
    public $parsedBody;
```
And these to `Imefisto\PsrSwoole\Request`
```
    public $swooleRequest;
    public $uriFactory;
    public $streamFactory;
    public $requestTarget;
    public $method;
    public $uri;
    public $protocol;
    public $body;
```
Public visibility to prevent breaking changes and no type hinting because I believe it is not supported before PHP 7.3.

If you wish I could send a PR

Thanks!

### PR DESCRIPTION
**Pull request by jsanahuja**
Closes #9.

Thanks!

### CODE REVIEW

**Comment by jsanahuja** [comment]
Also, the current version of PHPUnit doesn't seem to be compatible with PHP 8.2:
```
  Problem 1
    - phpspec/prophecy is locked to version 1.13.0 and an update of this package was not requested.
    - phpspec/prophecy 1.13.0 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.2.3) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy 1.13.0 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.2.3) does not satisfy that requirement.
    - phpunit/phpunit 8.5.16 requires phpspec/prophecy ^1.10.3 -> satisfiable by phpspec/prophecy[1.13.0].
    - phpunit/phpunit is locked to version 8.5.16 and an update of this package was not requested.
```
Updating it from `8.5.16` to `8.5.32` (no breaking changes) fixes it:
```
composer update phpunit/phpunit -W
```
But **I haven't been able to pass the tests** either way

PS: Tested with docker image `openswoole/swoole:php8.2-alpine` as follows:
```
docker run -it --rm --entrypoint composer -v ${PWD}:/app -w /app openswoole/swoole:php8.2-alpine update phpunit/phpunit -W
docker run -it --rm --entrypoint composer -v ${PWD}:/app -w /app openswoole/swoole:php8.2-alpine install
docker run -it --rm --entrypoint composer -v ${PWD}:/app -w /app openswoole/swoole:php8.2-alpine run test
```

**Comment by imefisto** [comment]
Thank you for the PR! 

I see why the tests are not passing after your changes: it breaks the first evaluation on `getParsedBody` in order to decide if return the `$this->parsedBody` value or `$this->swooleRequest->post` array:

```    
public function getParsedBody()
    {
        if (property_exists($this, 'parsedBody')) {
            return $this->parsedBody;
        }
        if (!empty($this->swooleRequest->post)) {
            return $this->swooleRequest->post;
        }

        return null;
    }
```

On the original version, the property_exists function returns false if no parsed body is set. With your PR, it resolves to true and that is breaking the test.

I see two approaches here:

1. Initialize `parsedBody` property with a non object, non array and non null value (this default value should return `false` on the `withParsedBody` evaluation). Then use the same conditions on `getParsedBody` to decide if returns `$this->parsedBody` or `$this->swooleRequest->post`:

```
    public $parsedBody = -1;

// code ...

    public function getParsedBody()
    {
        if (\is_object($this->parsedBody) || \is_array($this->parsedBody) || \is_null($this->parsedBody)) {
            return $this->parsedBody;
        }
        
        if (!empty($this->swooleRequest->post)) {
            return $this->swooleRequest->post;
        }

        return null;
    }

```

2. Instead of your changes, take advantage of the new introduced annotation `#[\AllowDynamicProperties]` ([See docs](https://www.php.net/manual/en/class.allowdynamicproperties.php))

On PHP 8.2, the first approach does not allow new properties to be added to the request object, which may be something good in order to prevent unplanned alterations. However it could break someone's code who relies on this possibility. 

The second approach ensures the warning won't show up on PHP 8.2 and maybe is more friendly with previous versions. What do you think?

**Comment by jsanahuja** [comment]
The errors I was getting come from [here](https://github.com/sebastianbergmann/phpunit/issues/4879), a lot of errors like:
```
58) Imefisto\PsrSwoole\Testing\ServerRequestTest::withoutAttributeInexistent
Error: Call to undefined method ReflectionUnionType::getName()
```
Which seems to be an issue of PHPUnit 8.5.X for PHP >= 8.1. I have tested with PHP 7.4 and saw what you are talking about.

In my opinion, the neatest thing to do is to opt for the first option doing something like this:
```diff
diff --git a/src/ServerRequest.php b/src/ServerRequest.php
index 3080742..2c8c37e 100644
--- a/src/ServerRequest.php
+++ b/src/ServerRequest.php
@@ -16,7 +16,7 @@ class ServerRequest extends Request implements ServerRequestInterface
     public $cookies;
     public $query;
     public $files;
-    public $parsedBody;
+    public $parsedBody = false;
 
     public function __construct(
         SwooleRequest $swooleRequest,
@@ -87,7 +87,7 @@ class ServerRequest extends Request implements ServerRequestInterface
 
     public function getParsedBody()
     {
-        if (property_exists($this, 'parsedBody')) {
+        if ($this->parsedBody !== false) {
             return $this->parsedBody;
         }
```
But I understand that the second option is the less dangerous to breaking changes. 

It's your repository so you decide, and whatever you decide will be fine for me 😄

**Comment by imefisto** [comment]
I'll go for the less dangerous option. I'll add the annotation `AllowDynamicProperties`.

Thank you very much for your insights.

Note 1: The reason behind checking for null|array|object explicitly was taken from psr7 specification for the [getParsedBody](https://www.php-fig.org/psr/psr-7/) method. 

Note 2: You're right about the phpunit errors: according to its creator, it's due incompatibility between phpunit v8.5 being used to test PHP 7 code. The thing is that updating to phpunit9 and/or 10 makes the thing worst in terms of errors, as they're removing several methods, so I'll have to redesign the tests in this project in order to work on PHP 8.2.

Thank you again.

**Pull request closed without merging**
