### PR TITLE
"getUploadedFiles" estava retornando o " $this->files" quando não existia upload. ajeitado foreach de "$this->swooleRequest->files as $name => $fileData" para "$this->swooleRequest->files ?? [] as $name => $fileData"

### PR DESCRIPTION
**Pull request by natanduty2014**
"getUploadedFiles" estava retornando o " $this->files" quando não existia upload. ajeitado foreach de "$this->swooleRequest->files as $name => $fileData" para "$this->swooleRequest->files ?? [] as $name => $fileData"

### CODE REVIEW

**Comment by mrceperka** [comment]
Got the same problem, would be nice to merge :pray:

**Comment by imefisto** [comment]
Hi! Thanks por the PR.  Merging now.

**Comment by imefisto** [comment]
I'll take a deep look later. What happens if you call getUploadedFiles twice?

**Comment by imefisto** [comment]
Ok. I've finished the review. The key for your fix was the addition of the `$this->swooleRequest->files ?? []` (nice catch, thank you!). I'll back to the original code to keep the early return in place but with your addition. Also I'll add a test for it.

**Pull request merged**
